### ISSUE TITLE
I have a problem caused by a dependency chain, can you help me?

### ISSUE THREAD

**Issue by lvzhenbo** [becem-gharbi/nuxt-naiveui#85]
I built the nuxt app and got it running, but the 500
```
Listening on http://[::]:3000
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read properties of undefined (reading 'userAgent')
    at file:///C:/Users/29422/Desktop/jav-pg-lib/.output/server/chunks/build/_num_-CzRuuTO6.mjs:1356:72
```
So I went looking for the problem and found the following code that reported an error after the build
```
var global = {};
var cache = /* @__PURE__ */ new WeakMap();
var scrollRegexp = /auto|scroll/;
var verticalRegexp = /^tb|vertical/;
var IE = /msie|trident/i.test(globalThis.navigator && global.navigator.userAgent);
```
Then the sourcemap found the @juggle/resize-observer dependency, and looked upwards to see that it was the vueuc dependency used by the
```
vueuc@0.4.64(vue@3.5.13(typescript@5.7.3)):
    dependencies:
      '@css-render/vue3-ssr': 0.15.14(vue@3.5.13(typescript@5.7.3))
      '@juggle/resize-observer': 3.4.0
      css-render: 0.15.14
      evtd: 0.2.4
      seemly: 0.3.10
      vdirs: 0.1.8(vue@3.5.13(typescript@5.7.3))
      vooks: 0.2.12(vue@3.5.13(typescript@5.7.3))
      vue: 3.5.13(typescript@5.7.3)
```
At this point I went to the source code of @juggle/resize-observer, and sure enough it was a problem with this package, or the packaged code of this package.
I temporarily removed the userAgent field and found that the problem was solved, but that's not a solution, can you help me?
